---
- name: clone latest ffmpeg
  git:
    repo: "https://github.com/FFmpeg/FFmpeg.git"
    dest: "{{ ffmpeg_source_dir }}/ffmpeg"
    update: no

- name: compile ffmpeg
  command: "{{ item }}"
  args:
     chdir: "{{ ffmpeg_source_dir }}/ffmpeg"
     creates: "{{ ffmpeg_bin_dir }}/ffmpeg"
  environment: ffmpeg_env
  with_items:
    - ./configure --prefix="{{ ffmpeg_build_dir }}" --pkg-config-flags="--static" --extra-cflags="-I{{ ffmpeg_build_dir }}/include" --extra-ldflags="-L{{ ffmpeg_build_dir }}/lib" --bindir="{{ ffmpeg_bin_dir }}" --extra-libs=-ldl --enable-gpl --enable-libass --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-libxvid
    - make
    - make install
    - make distclean
