---
- name: apt-get update
  sudo: true
  apt: update_cache=yes cache_valid_time=3600
  
- name: install dependencies
  sudo: true
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - autoconf 
    - automake 
    - build-essential 
    - pkg-config
    - libtool
    - libass-dev 
    - libgpac-dev
    - libsdl1.2-dev 
    - libtheora-dev 
    - libva-dev 
    - libvdpau-dev 
    - libvorbis-dev 
    - texi2html 
    - zlib1g-dev
    - libmp3lame-dev
    - libopenjpeg-dev
    - libxvidcore-dev
    - libfreetype6-dev
    - libfaac-devi
    - libfaad-dev
    - libdirac-dev