---
- name: clone latest yasm
  git:
    repo: "https://github.com/yasm/yasm.git"
    dest: "{{ ffmpeg_source_dir }}/yasm"
    update: no

- name: compile yasm
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/yasm"
    creates: "{{ ffmpeg_bin_dir }}/yasm"
  with_items:
    - ./autogen.sh
    - ./configure --prefix={{ ffmpeg_build_dir }} --bindir={{ ffmpeg_bin_dir }}
    - make
    - make install
    - make distclean
