---
- name: clone latest yasm
  git:  repo=git://github.com/yasm/yasm.git dest={{ ffmpeg_source_dir }}/yasm update=no

- name: compile yasm 
  command: "{{ item }} chdir={{ ffmpeg_source_dir }}/yasm creates={{ ffmpeg_bin_dir }}/yasm"
  with_items:
    - ./autogen.sh
    - ./configure --prefix={{ ffmpeg_build }} --bindir={{ ffmpeg_bin_dir }}
    - make
    - sudo make install
    - make distclean