---
- name: clone latest fdk-aac
  git:  repo=git://github.com/mstorsjo/fdk-aac.git dest={{ ffmpeg_source_dir }}/fdk-aac update=no

- name: compile fdk-aac
  command: "{{ item }} chdir={{ ffmpeg_source_dir }}/fdk-aac creates={{ ffmpeg_build }}/lib/libfdk-aac.a"
  with_items:
    - autoreconf -fiv
    - ./configure --prefix={{ ffmpeg_build }} --disable-shared
    - make
    - sudo make install
    - make distclean
