---
- name: clone latest fdk-aac
  git:
    repo: "https://github.com/mstorsjo/fdk-aac.git"
    dest: "{{ ffmpeg_source_dir }}/fdk-aac"
    update: no

- name: compile fdk-aac
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/fdk-aac"
    creates: "{{ ffmpeg_build_dir }}/lib/libfdk-aac.a"
  with_items:
    - autoreconf -fiv
    - ./configure --prefix={{ ffmpeg_build_dir }} --disable-shared
    - make
    - make install
    - make distclean
