---
- name: clone latest libvpx
  git:
    repo: "https://chromium.googlesource.com/webm/libvpx.git"
    dest: "{{ ffmpeg_source_dir }}/libvpx"
    update: no

- name: compile libvpx
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/libvpx"
    creates: "{{ ffmpeg_build_dir }}/lib/libvpx.a"
  environment: ffmpeg_env
  with_items:
    - ./configure --prefix={{ ffmpeg_build_dir }} --disable-shared --disable-examples --disable-unit-tests
    - make
    - make install
    - make clean
