---
- name: clone latest opus
  git:
    repo: "git://git.opus-codec.org/opus.git"
    dest: "{{ ffmpeg_source_dir }}/opus"
    update: no
    accept_hostkey: yes

- name: compile libopus
  command: "{{ item }}"
  args:
    chdir: "{{ ffmpeg_source_dir }}/opus"
    creates: "{{ ffmpeg_build_dir }}/lib/libopus.a"
  with_items:
    - ./autogen.sh
    - ./configure --prefix={{ ffmpeg_build_dir }} --disable-shared
    - make
    - make install
    - make distclean
