---
- name: clone latest x264
  git:  repo=git://git.videolan.org/x264.git dest={{ ffmpeg_source_dir }}/x264 update=no
    
- name: compile x264
  shell: "{{ item }} chdir={{ ffmpeg_source_dir }}/x264 creates={{ ffmpeg_bin_dir }}/x264"
  environment: ffmpeg_env
  with_items:
    - ./configure --prefix={{ ffmpeg_build }} --bindir={{ ffmpeg_bin_dir }} --enable-static
    - make
    - sudo make install
    - make distclea
